[package]
name = "tiny-kv"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
prost = "0.13.5"
tonic = "0.13.0"
tokio = { version = "1.44.2", features = ["full"] }
tonic-reflection = "0.13.0"

[build-dependencies]
tonic-build = "0.13.0"
